server:
  port: 8080

spring:
  application:
    name: DDIS_Project

  security:
    user:
      name: none
      password: none

  ## jpa config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/ddis       #각자 수정
    username: root                                #각자 수정
    password: 1123                                #각자 수정